[ADD] modeling
wecode-bootcamp-korea/29-1st-FRESH-EZ-backend pull request #1
Opened 2022-01-25 10:12 UTC by DongKey777

## [ADD] modeling
- user 모델 추가
- product 모델 추가
- subscription 모델 추가
- order 모델 추가

2022-01-25 14:27 UTC, lordmyshepherd requested changes

2022-01-25 14:27 UTC, lordmyshepherd commented on order/models.py
> +# Create your models here.
주석은 지워주세요~!

2022-01-25 14:27 UTC, lordmyshepherd commented on order/models.py
> +        db_table = 'order_status'
python에서 class명은 CameCase를 사용해주세요-!

2022-01-25 14:27 UTC, lordmyshepherd commented on order/models.py
> +class Order_Item_Status(models.Model):
마찬가지입니다.

2022-01-25 14:27 UTC, lordmyshepherd commented on order/models.py
> +class Order_Item(models.Model):
마찬가지로 위에서 드린 피드백 반영해주세요~

2022-01-25 14:27 UTC, lordmyshepherd commented on product/models.py
> +# Create your models here.
주석은 지워주세요~

2022-01-25 14:27 UTC, lordmyshepherd commented on product/models.py
> +class Sub_Category(models.Model):
```suggestion
class SubCategory(models.Model):
```

2022-01-25 14:27 UTC, lordmyshepherd commented on product/models.py
> +    option_image3 = models.ImageField()
image는 ProductImage 테이블로 분리해주세요~

2022-01-25 14:27 UTC, lordmyshepherd commented on product/models.py
> +    allergies = models.ForeignKey(Allergy, on_delete=models.DO_NOTHING)
allergies는 Many to Many 관계 아닌가요?

2022-01-25 14:27 UTC, lordmyshepherd commented on product/models.py
> +    product = models.ForeignKey(Product, on_delete=models.DO_NOTHING)
중간테이블을 위한 Class명은 각 class명을 합쳐서 만들어주세요.
아래 코드 참고 바랍니다.
```suggestion
class ProductAllergy(models.Model):
    allergy = models.ForeignKey(Allergy, on_delete=models.DO_NOTHING)
    product = models.ForeignKey(Product, on_delete=models.DO_NOTHING)
```

2022-01-25 14:27 UTC, lordmyshepherd commented on product/models.py
> +        db_table = 'product_allergies_joined'
중간 테이블의 경우 
- class명은 단수+단수
- 테이블명은 복수+복수로 만들어주세요.

2022-01-25 14:27 UTC, lordmyshepherd commented on user/models.py
> +class User_Allergies_Joined(models.Model):
위에서 피드백 드린대로 class명, table명 수정해주세요~

2022-01-26 04:39 UTC, DongKey777 commented
병민님 피드백 감사합니다 !
피드백 반영하여 새로 푸쉬했습니다 !

2022-01-26 06:26 UTC, lordmyshepherd requested changes

2022-01-26 06:26 UTC, lordmyshepherd commented on order/models.py
> +
SellingCount는 뭔가요?

2022-01-26 06:26 UTC, lordmyshepherd commented on order/models.py
> +
왜 필요한가요??

2022-01-26 06:26 UTC, lordmyshepherd commented on product/models.py
> +        db_table = 'products_images'
product image가 product를 FK로 참조하고 있어야하지 않을까요?
컬럼명도 verbose 하지 않고 간결하고 명확하게 만들어주세요~

```suggestion
class ProductImage(models.Model):
    product = models.ForeignKey(Product,on_delete=models.DO_NOTHING, null=False)
    image_url = models.ImageField()

    class Meta:
        db_table = 'product_images'
```

2022-01-26 06:58 UTC, DongKey777 commented
피드백 반영하여 수정완료했습니다.
- ProductImage 테이블에 product fk 추가
- Subscription 테이블에 product fk 추가

2022-01-26 06:59 UTC, DongKey777 commented on order/models.py
> +
가장 많이 구매한 샐러드를 추천해주는 기능을 구현하고자 하여
상품별 구매횟수를 관리하는 테이블을 생성했습니다.

2022-01-26 08:59 UTC, lordmyshepherd commented
LGTM 👍🏻

2022-01-26 09:01 UTC, merged