[29기 이도운] 구독 상품 가격 리스트 기능 구현
wecode-bootcamp-korea/29-1st-FRESH-EZ-backend pull request #29
Opened 2022-02-09 08:14 UTC by wepungsan

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 카테고리별 구독 상품 가격 리스트를 반환하는 기능을 구현합니다.

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 캍테고리별 구독 상품 가격 리스트 반환

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

<br />

## :: 기타 질문 및 특이 사항

2022-02-09 09:12 UTC, lordmyshepherd requested changes

2022-02-09 09:12 UTC, lordmyshepherd commented on product/views.py
> +        })
PR 제목은 구독 상품 가격 리스트 구현이라고 되어 있는데 코드는 상품 목록을 반환하는 것 처럼 보이네요?

어떤 기능을 구현하고자 하는지 자세히 알려주실 수 있을까요?

2022-02-09 14:43 UTC, wepungsan commented on product/views.py
> +        })
말씀 그대로 구독 상품 가격 리스트를 반환하는 것입니다. 다만 구독 상품 가격은 단품 5개를 합친 가격이기에 각 카테고리 별로 단품 5개 가격을 반환하고 있는 것입니다. ☺

2022-02-10 01:57 UTC, lordmyshepherd requested changes

2022-02-10 01:57 UTC, lordmyshepherd commented on product/views.py
> +        })
이부분은 구두로 리뷰가 필요할 것 같습니다. 2시에 라운지에서 뵐게요~

2022-02-10 05:18 UTC, lordmyshepherd commented
LGTM 👍🏻

2022-02-10 05:18 UTC, merged